from .env import MedicalConsultationEnv
from .env_patient_llm import MedicalConsultationEnvWithPatientLLM
from .env_patient_llm_rm import MedicalConsultationEnvWithPatientLLMandRM
# 明确使用 env_patient_llm_category.py（有 RAG 功能 + 完整监控指标）
# 不要切换到 env_patient_llm_category_full_reward.py 或 env_patient_llm_category_simple.py
from .env_patient_llm_category import MedicalConsultationEnvWithPatientLLMCategory
